language: node_js
node_js:
  - node

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8

script:
  - yarn build
  - yarn test:ci

notifications:
  webhooks:
    urls:
      - https://api.netlify.com/build_hooks/5c9ce3d0f9d4a5018b13ef93
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never

