language: node_js
node_js:
  - node

script:
  - yarn build
  - yarn test:ci

notifications:
  webhooks:
    urls:
      - https://api.netlify.com/build_hooks/5c9ce3d0f9d4a5018b13ef93
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always

