version: '3'
services:
  site:
    container_name: site
    build: .
    image: josephthomashines/site
    ports:
      - "5001:5001"
    environment:
      - TZ="America/New_York"
    restart: always
